# Generated by Django 6.0.1 on 2026-01-25 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garage', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyCarStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('trips_count', models.PositiveIntegerField(default=0)),
                ('total_distance_km', models.PositiveIntegerField(default=0)),
                ('refuels_count', models.PositiveIntegerField(default=0)),
                ('total_fuel_liters', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_fuel_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_stats', to='garage.car')),
            ],
            options={
                'ordering': ('-year', '-month'),
                'unique_together': {('car', 'year', 'month')},
            },
        ),
    ]
