# Generated by Django 6.0.1 on 2026-01-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garage', '0001_initial'),
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='cars', to='logbook.tag'),
        ),
        migrations.AlterUniqueTogether(
            name='car',
            unique_together={('owner', 'brand', 'model', 'year')},
        ),
    ]
